### ISSUE TITLE
java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by nobus** [Favouriteless/Enchanted#16]
**Describe the bug**
 
When I started Minecraft, I got Error "The game crashed whilst initializing game
Error: java.lang.ExceptionInInitializerError: null" and code 255.
Also I got the report:
```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2024-04-15 20:27:29
Description: Initializing game

java.lang.ExceptionInInitializerError: null
	at com.favouriteless.enchanted.client.ClientRegistry.registerParticleFactories(ClientRegistry.java:67) ~[Enchanted-forge-1.19.2-2.0.2.jar%23145!/:2.0.2] {re:mixin,re:classloading}
	at net.minecraft.client.particle.ParticleEngine.handler$zzc000$init(ParticleEngine.java:582) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enchanted.mixins.json:ParticleEngineMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleEngine.m_107404_(ParticleEngine.java:178) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enchanted.mixins.json:ParticleEngineMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleEngine.<init>(ParticleEngine.java:81) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enchanted.mixins.json:ParticleEngineMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:517) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.9.jar%2389!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.getModEventBus()" because the return value of "net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.get()" is null
	at com.favouriteless.enchanted.platform.services.ForgeCommonRegistryHelper$RegistryMap.lambda$register$0(ForgeCommonRegistryHelper.java:110) ~[Enchanted-forge-1.19.2-2.0.2.jar%23145!/:2.0.2] {re:classloading}
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?] {}
	at com.favouriteless.enchanted.platform.services.ForgeCommonRegistryHelper$RegistryMap.register(ForgeCommonRegistryHelper.java:103) ~[Enchanted-forge-1.19.2-2.0.2.jar%23145!/:2.0.2] {re:classloading}
	at com.favouriteless.enchanted.platform.services.ForgeCommonRegistryHelper.register(ForgeCommonRegistryHelper.java:44) ~[Enchanted-forge-1.19.2-2.0.2.jar%23145!/:2.0.2] {re:classloading}
	at com.favouriteless.enchanted.common.init.registry.EnchantedParticleTypes.register(EnchantedParticleTypes.java:44) ~[Enchanted-forge-1.19.2-2.0.2.jar%23145!/:2.0.2] {re:classloading}
	at com.favouriteless.enchanted.common.init.registry.EnchantedParticleTypes.<clinit>(EnchantedParticleTypes.java:17) ~[Enchanted-forge-1.19.2-2.0.2.jar%23145!/:2.0.2] {re:classloading}
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at com.favouriteless.enchanted.client.ClientRegistry.registerParticleFactories(ClientRegistry.java:67) ~[Enchanted-forge-1.19.2-2.0.2.jar%23145!/:2.0.2] {re:mixin,re:classloading}
	at net.minecraft.client.particle.ParticleEngine.handler$zzc000$init(ParticleEngine.java:582) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enchanted.mixins.json:ParticleEngineMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleEngine.m_107404_(ParticleEngine.java:178) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enchanted.mixins.json:ParticleEngineMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleEngine.<init>(ParticleEngine.java:81) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enchanted.mixins.json:ParticleEngineMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:517) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.9.jar%2389!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

```

**To Reproduce**
I used:
- Ubuntu 22.04.4 LTS
- official Minecraft loader
- Minecraft release 1.19.2 
- forge-1.19.2-43.3.9
- mod's list:
  * geckolib-forge-1.19-3.1.40.jar
  * Patchouli-1.19.2-77.jar
  * StateObserver-forge-1.19.2-1.3.1.jar
  * Enchanted-forge-1.19.2-2.0.2.jar (also I tried 2.0.1 and 2.0.0 - similar error)

**Comment by Favouriteless** [comment]
I was really hoping something like this wouldn't happen. Just booted the game with an identical setup to yours on Windows 11 and it seems to be fine, so this looks like a Linux issue. Might take me a while to investigate this.

**Comment by Favouriteless** [comment]
Apologies, this is actually NOT a linux issue. You're missing a dependency SmartBrainLib the mod will work fine if you install it. No idea why Forge isn't notifying about the missing dependency.

**Comment by nobus** [comment]
> Apologies, this is actually NOT a linux issue. You're missing a dependency SmartBrainLib the mod will work fine if you install it. No idea why Forge isn't notifying about the missing dependency.

Yes, it's working!! Thnks you!!! =)
Maybe need to point SmartBrainLib in this place? 
https://www.curseforge.com/minecraft/mc-mods/enchanted-witchcraft/relations/dependencies
