### ISSUE TITLE
2x6 Altar causes a game crash when loading the area it is located.

### ISSUE THREAD

**Issue by tierghan** [Favouriteless/Enchanted#4]
**Describe the bug**
I personaly have never played this mod, but i have used Witchery. Either way, i run a modded server and this mod is in the pack i am running, and one of my players made a 2x6 altar and on the placement of the last block, it caused his game to crash, as well as another players game to crash when they got to the location. I fixed this by using the console to /setblock one of the altar blocks to bedrock, and this fixed things.

**To Reproduce**
Make a 2x6 altar. See sc for full area context, and replace the bedrock with an altar.

**Expected behavior**
Not crashing the game upon rendering.
**Screenshots**
![image](https://user-images.githubusercontent.com/50425512/185547420-8282ac01-4c5c-42dd-869d-26dfd1c1cad5.png)

Full Crash report:
`---- Minecraft Crash Report ----
// Don't do that.

Time: 8/19/22 12:58 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraftforge.fml.LogicalSidedProvider.lambda$static$3(LogicalSidedProvider.java:33) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.LogicalSidedProvider$$Lambda$2920/650621382.apply(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.LogicalSidedProvider.get(LogicalSidedProvider.java:60) ~[?:?] {re:classloading}
	at hellfirepvp.observerlib.common.data.WorldCacheDomain.getSaveDirectory(WorldCacheDomain.java:105) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.data.WorldCacheIOThread.loadDataFromFile(WorldCacheIOThread.java:141) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.data.WorldCacheIOThread.loadNow(WorldCacheIOThread.java:106) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.data.WorldCacheDomain.getData(WorldCacheDomain.java:96) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.api.MatcherObserverHelper.getBuffer(MatcherObserverHelper.java:34) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.api.MatcherObserverHelper.getSubscriber(MatcherObserverHelper.java:51) ~[?:1.16.5-1.5.3] {re:classloading}
	at com.favouriteless.enchanted.common.tileentity.AltarTileEntity.func_73660_a(AltarTileEntity.java:130) ~[?:1.1.2] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:175) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1485) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$494/564143446.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.LogicalSidedProvider.lambda$static$3(LogicalSidedProvider.java:33) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.LogicalSidedProvider$$Lambda$2920/650621382.apply(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.LogicalSidedProvider.get(LogicalSidedProvider.java:60) ~[?:?] {re:classloading}
	at hellfirepvp.observerlib.common.data.WorldCacheDomain.getSaveDirectory(WorldCacheDomain.java:105) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.data.WorldCacheIOThread.loadDataFromFile(WorldCacheIOThread.java:141) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.data.WorldCacheIOThread.loadNow(WorldCacheIOThread.java:106) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.data.WorldCacheDomain.getData(WorldCacheDomain.java:96) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.api.MatcherObserverHelper.getBuffer(MatcherObserverHelper.java:34) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.api.MatcherObserverHelper.getSubscriber(MatcherObserverHelper.java:51) ~[?:1.16.5-1.5.3] {re:classloading}
	at com.favouriteless.enchanted.common.tileentity.AltarTileEntity.func_73660_a(AltarTileEntity.java:130) ~[?:1.1.2] {re:classloading}
-- Block entity being ticked --
Details:
	Name: enchanted:altar // com.favouriteless.enchanted.common.tileentity.AltarTileEntity
	Block: Block{enchanted:altar}[facing_x=false,formed=p000]
	Block location: World: (553,67,-2168), Chunk: (at 9,4,8 in 34,-136; contains blocks 544,0,-2176 to 559,255,-2161), Region: (1,-5; contains chunks 32,-160 to 63,-129, blocks 512,0,-2560 to 1023,255,-2049)
	Block: Block{enchanted:altar}[facing_x=false,formed=p000]
	Block location: World: (553,67,-2168), Chunk: (at 9,4,8 in 34,-136; contains blocks 544,0,-2176 to 559,255,-2161), Region: (1,-5; contains chunks 32,-160 to 63,-129, blocks 512,0,-2560 to 1023,255,-2049)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:175) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['tierghan'/2690, l='ClientLevel', x=528.50, y=67.00, z=-2160.50]]
	Chunk stats: Client Chunk Cache: 729, 484
	Level dimension: minecraft:overworld
	Level spawn location: World: (-25,64,-254), Chunk: (at 7,4,2 in -2,-16; contains blocks -32,0,-256 to -17,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 24431274 game time, 427313 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$494/564143446.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3472926664 bytes (3312 MB) / 14582546432 bytes (13907 MB) up to 31973703680 bytes (30492 MB)
	CPUs: 8
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx34304m -Xms256m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		scorge@3.1.3
	Mod List: 
		inventorysorter-1.16.1-18.1.0.jar                 |Simple Inventory Sorter       |inventorysorter               |18.1.0              |DONE      |Manifest: NOSIGNATURE
		Corail-Adventurer-Spawners-1.16.5-020.jar         |Corail Adventurer Spawners    |corail_adventurer_spawners    |1.16.5-020          |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.16.5-5.1.jar                      |Tree Harvester                |treeharvester                 |5.1                 |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
		SlashBlade-1.16-0.0.12.1.jar                      |Slash Blade                   |slashblade                    |0.0.12              |DONE      |Manifest: NOSIGNATURE
		All_RecipesV1.1.1(1.16.5).jar                     |All Recipes                   |all_recipes                   |1.0.0               |DONE      |Manifest: NOSIGNATURE
		mot-1.16.5-b1.0.jar                               |Masks of Terror               |mot                           |b1.0                |DONE      |Manifest: NOSIGNATURE
		LibraryFerret-Forge-1.16.5-2.5.1.jar              |Library Ferret                |libraryferret                 |2.5.1               |DONE      |Manifest: NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.16.5-7.2.2.0-build.0202.jar      |Forge Endertech               |forgeendertech                |7.2.2.0             |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p5.jar                     |Journeymap                    |journeymap                    |5.8.5p5             |DONE      |Manifest: NOSIGNATURE
		Controlling-7.0.0.28.jar                          |Controlling                   |controlling                   |7.0.0.28            |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  |DONE      |Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.16.5-1.5.3.jar             |Simple Storage Network        |storagenetwork                |1.16.5-1.5.3        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		AdHooks-1.16.5-6.1.8.1-build.0210.jar             |Advanced Hook Launchers       |adhooks                       |6.1.8.1             |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.32.jar                |Bookshelf                     |bookshelf                     |10.4.32             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.16.5-3.15.16.669.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.15.16.669  |DONE      |Manifest: NOSIGNATURE
		deathmatch-1.0.1v.jar                             |Deathmatch                    |deathmatch                    |1.0.1               |DONE      |Manifest: NOSIGNATURE
		Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus                      |4.2.70              |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.1.2.457.jar          |Mekanism: Generators          |mekanismgenerators            |10.1.2              |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		WAWLA-1.16.5-8.0.9.jar                            |WAWLA                         |wawla                         |8.0.9               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		JEITweaker-1.16.5-1.1.0.49.jar                    |JEI Tweaker                   |jeitweaker                    |1.1.0.49            |DONE      |Manifest: NOSIGNATURE
		inventorypets-1.16.5-2.0.15.jar                   |Inventory Pets                |inventorypets                 |2.0.15              |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-1.16.5-7.1.2.511.jar                 |CraftTweaker                  |crafttweaker                  |7.1.2.511           |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.1.2.457.jar                    |Mekanism                      |mekanism                      |10.1.2              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		spatialharvesters_Forge_1.16.5-0.11.11.jar        |Spatial Harvesters            |spatialharvesters             |0.11.11             |DONE      |Manifest: NOSIGNATURE
		metal_gear_rising_relics_0.7_1.16.5.jar           |metal gear risnig relics      |metal_gear_risnig_relics      |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Crated_Vanilla_Foods_1.1-1.16.5.jar               |EggCrate                      |eggcrate                      |1.0.0               |DONE      |Manifest: NOSIGNATURE
		CraftingTweaks_1.16.5-12.2.1.jar                  |Crafting Tweaks               |craftingtweaks                |12.2.1              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.6.0.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.6.0        |DONE      |Manifest: NOSIGNATURE
		The Time Mod.jar                                  |time stop mod                 |time_stop_mod                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		voicechat-forge-1.16.5-2.3.2.jar                  |Simple Voice Chat             |voicechat                     |1.16.5-2.3.2        |DONE      |Manifest: NOSIGNATURE
		[1.16.5] Vertical Slabs and Panels-1.1.jar        |Vertical Slabs And Panels     |vertical_slabs_and_panels     |1.1.0               |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |Manifest: NOSIGNATURE
		MekanismAdditions-1.16.5-10.1.2.457.jar           |Mekanism: Additions           |mekanismadditions             |10.1.2              |DONE      |Manifest: NOSIGNATURE
		RelicsOfGaming1.16.5-1.0.4.jar                    |Relics Of Gaming              |rog                           |1.0.4               |DONE      |Manifest: NOSIGNATURE
		MJs Animations 1.1.1 (1.16.5).jar                 |MJs Animations                |mjs_animations                |1.1.1               |DONE      |Manifest: NOSIGNATURE
		UnusualEnd1.16_V1.1.4.jar                         |Unusual End                   |unusualend                    |1.1.0               |DONE      |Manifest: NOSIGNATURE
		easy_villagers-1.16.5-1.0.13.jar                  |Easy Villagers                |easy_villagers                |1.16.5-1.0.13       |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.2      |DONE      |Manifest: NOSIGNATURE
		relics-1.16.5-0.3.4.3.jar                         |Relics                        |relics                        |0.3.4.3             |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |DONE      |Manifest: NOSIGNATURE
		collective-1.16.5-4.37.jar                        |Collective                    |collective                    |4.37                |DONE      |Manifest: NOSIGNATURE
		[Forge-1.16.5] Hololive Relics (6.1.1).jar        |Hololive Relics               |hololive_relics               |6.1.1               |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.40.jar                   |Polymorph                     |polymorph                     |1.16.5-0.40         |DONE      |Manifest: NOSIGNATURE
		OreExcavation-1.8.157.jar                         |Ore Excavation                |oreexcavation                 |1.8.157             |DONE      |Manifest: e7:68:1c:0d:b9:7e:cf:f8:f3:40:9c:84:c5:39:d7:a4:59:78:b0:6b:c3:fd:b7:4f:69:18:a3:88:e3:76:8c:3f
		FluxNetworks-1.16.5-6.2.1.14.jar                  |Flux Networks                 |fluxnetworks                  |6.2.1.14            |DONE      |Manifest: NOSIGNATURE
		obfuscate-0.6.3-1.16.5.jar                        |Obfuscate                     |obfuscate                     |0.6.3               |DONE      |Manifest: NOSIGNATURE
		RedstoneMagic-1.16.4-1.16.5-1.4.0.37.jar          |Redstone Magic                |redstonemagic                 |1.16.5-1.4.0.37     |DONE      |Manifest: NOSIGNATURE
		Unusual_Drill_1.16.5_V2.1.jar                     |Unusual Drill Mod             |unusual_drill_mod             |2.0                 |DONE      |Manifest: NOSIGNATURE
		TheAbyss2 2.2.3-4 1.16.5.jar                      |TheAbyss                      |theabyss                      |2.2.3-4             |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.1.2.457.jar               |Mekanism: Tools               |mekanismtools                 |10.1.2              |DONE      |Manifest: NOSIGNATURE
		alwaysawitherskull_1.16.5-1.4.jar                 |Always a Wither Skull         |alwaysawitherskull            |1.4                 |DONE      |Manifest: NOSIGNATURE
		sekiro_mod_b_0.0.5.jar                            |Sekiro_Mod                    |sekiro_mod                    |0.0.5               |DONE      |Manifest: NOSIGNATURE
		observerlib-1.16.5-1.5.3.jar                      |ObserverLib                   |observerlib                   |1.16.5-1.5.3        |DONE      |Manifest: NOSIGNATURE
		half_life_relics_0.8_1.16.5.jar                   |Half life Relics              |half_life_relics              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		enchanted-1.16.5-1.1.2.jar                        |Enchanted                     |enchanted                     |1.1.2               |DONE      |Manifest: NOSIGNATURE
		TheLegendOfHerobrine-1.16.5-0.6.3.jar             |The Legend of Herobrine       |herobrine                     |0.6.3               |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-v25.2.jar                           |FastLeafDecay                 |fastleafdecay                 |v25.2               |DONE      |Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.7.445-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.7.445           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		CBMultipart-1.16.5-3.0.4.123-universal.jar        |CBMultipart                   |cb_multipart                  |3.0.4.123           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		ProjectRed-1.16.5-4.12.0-core.jar                 |ProjectRed Core               |projectred-core               |4.12.0              |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.12.0-illumination.jar         |ProjectRed Illumination       |projectred-illumination       |4.12.0              |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.12.0-transmission.jar         |ProjectRed Transmission       |projectred-transmission       |4.12.0              |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.12.0-exploration.jar          |ProjectRed Exploration        |projectred-exploration        |4.12.0              |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.12.0-integration.jar          |ProjectRed Integration        |projectred-integration        |4.12.0              |DONE      |Manifest: NOSIGNATURE
		seteffect-1.16.5-1.0.8.jar                        |ArmorSetEffects               |seteffect                     |1.16.5-1.0.8        |DONE      |Manifest: NOSIGNATURE
		createaddition-1.16.5-20220129a.jar               |Create Crafts & Additions     |createaddition                |1.16.5-20220129a    |DONE      |Manifest: NOSIGNATURE
		alllootdrops_1.16.5-2.3.jar                       |All Loot Drops                |alllootdrops                  |2.3                 |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: cfb21a8a-7f03-4803-a011-6adde32061e7
	Patchouli open book context: n/a
	Launched Version: forge-36.2.34
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.23, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz`

**Comment by Favouriteless** [comment]
Fixed now pending an update some time this week, sorry for taking so long to get on this.

**Comment by tierghan** [comment]
No problem. Im not running the pack on the server anymore so i cannot
confirm if this still happens, but thank you for getting to it regardless.
