### ISSUE TITLE
[BUG]: Server Crash on Startup "Failed to read accessWidener... Fabric 1.21.1 onm 0.16.9

### ISSUE THREAD

**Issue by suerion** [Favouriteless/Enchanted#49]
### Please confirm the following

- [X] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [X] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.21.1

### Mod version

enchanted 4.0.2-beta

### Describe the bug

It crash the Server on Prelaunch from the Startup on accessWidener (Think Server/Client Compat ?)

```
[14:27:23] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod enchanted
        at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:529) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.9.jar:?]
        ... 1 more
Caused by: net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerFormatException: Namespace (named) does not match current runtime namespace (intermediary)
        at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:527) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.9.jar:?]
        ... 1 more
```

### Game Log

https://mclo.gs/BHFETk1

### Additional mods

Yes

### Mod List or Modpack

Huge Modpack, please look on Latest log for the Modlist

**Comment by Favouriteless** [comment]
Fixed, pending update

**Comment by suerion** [comment]
Thanks for letting me know, will look on update then :) thanks

**Comment by suerion** [comment]
On enchanted 4.0.3-beta it occurs again, think it would be an bigger update?

@Favouriteless

**Comment by Favouriteless** [comment]
> On enchanted 4.0.3-beta it occurs again, think it would be an bigger update?
> 
> @Favouriteless 

Can you confirm if it happens with just Enchanted and it's dependencies? Fabric is running fine on my end.

**Comment by suerion** [comment]
@Favouriteless with only Fabric and enchanted 
https://mclo.gs/qZU5YRg

**Comment by Favouriteless** [comment]
Forwarding this to the fabric team, as far as I can tell this appears to be some platform issue unrelated to Enchanted. Confirmed the mod functions as intended on my end with identical versions for everything
https://mclo.gs/agt3iH3

**Comment by suerion** [comment]
okey,
it is normal server version, not cracked, fabric server 0.16.9
Server is an Dedicated Root, Windows Server 2019


Will trying on my side on Windows 11, if it work
Same issue on Windows 11
https://mclo.gs/e9A0mv9
