### ISSUE TITLE
[BUG]: Game CRASHES because of Mandrake

### ISSUE THREAD

**Issue by Spicyramenn** [Favouriteless/Enchanted#58]
### Please confirm the following

- [x] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [x] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.20.1

### Mod version

1.20.1

### Describe the bug

Every time I throw the mandrake into the Cauldron my game crashes out. It gets to the point where I can no longer join my game

### Game Log

The game crashed whilst unexpected error Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$2" is null

### Additional mods

Yes

### Mod List or Modpack

- Farmer Delight
- [Lets do] Furniture
- Better Combat
- Combat+
- Cooking for blockheads
- Epic Knight
- Essential
- Farmers Delight Refab
- Farmers Knives
- Incendium
- Just Enough Items
- Just Enough Farmer's Recipes
- More tools
- Naturalist
- Serene Seasons
- Skin Layers
- Towns and Towers
- Tree Harvester
- Waystones
- Xaero minimap + world map

**Comment by Favouriteless** [comment]
I need the entire log, not just a tiny section of it.

**Comment by Spicyramenn** [comment]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-12-19 16:40:34
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$2" is null
	at knot//net.minecraft.class_291.method_34431(class_291.java:130)
	at knot//net.minecraft.class_291.method_34427(class_291.java:123)
	at knot//net.minecraft.class_286.method_43438(class_286.java:33)
	at knot//net.minecraft.class_286.method_43433(class_286.java:26)
	at knot//net.minecraft.class_289.method_1350(class_289.java:27)
	at knot//net.favouriteless.enchanted.client.EParticleRenderTypes$1.method_18131(EParticleRenderTypes.java:26)
	at knot//net.minecraft.class_702.method_3049(class_702.java:451)
	at knot//net.minecraft.class_761.redirect$cdo000$iris$renderTranslucentAfterDeferred(class_761.java:9979)
	at knot//net.minecraft.class_761.method_22710(class_761.java:1506)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1110)
	at knot//net.minecraft.class_757.method_3192(class_757.java:880)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1219)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_291.method_34431(class_291.java:130)
	at knot//net.minecraft.class_291.method_34427(class_291.java:123)
	at knot//net.minecraft.class_286.method_43438(class_286.java:33)
	at knot//net.minecraft.class_286.method_43433(class_286.java:26)
	at knot//net.minecraft.class_289.method_1350(class_289.java:27)
	at knot//net.favouriteless.enchanted.client.EParticleRenderTypes$1.method_18131(EParticleRenderTypes.java:26)
	at knot//net.minecraft.class_702.method_3049(class_702.java:451)
	at knot//net.minecraft.class_761.redirect$cdo000$iris$renderTranslucentAfterDeferred(class_761.java:9979)
	at knot//net.minecraft.class_761.method_22710(class_761.java:1506)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1110)

-- Affected level --
Details:
	All players: 1 total; [class_746['sP1cYram3nn'/372, l='ClientLevel', x=-47.78, y=69.00, z=152.74]]
	Chunk stats: 4096, 1393
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,76,32), Section: (at 0,12,0 in 4,4,2; chunk contains blocks 64,-64,32 to 79,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2621 game time, 2621 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at knot//net.minecraft.class_638.method_8538(class_638.java:458)
	at knot//net.minecraft.class_310.method_1587(class_310.java:2406)
	at knot//net.minecraft.class_310.method_1514(class_310.java:826)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, $polymer-resources, Essential Assets, essential

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1680328192 bytes (1602 MiB) / 3558866944 bytes (3394 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 4900H with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.29
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) RX 5600M Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=31.0.21024.5
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x1636
	Graphics card #1 versionInfo: DriverVersion=31.0.21024.5
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32269.07
	Virtual memory used (MB): 19063.51
	Swap memory total (MB): 16531.56
	Swap memory used (MB): 740.14
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		architectury: Architectury 9.2.14
		balm-fabric: Balm 7.3.10
			kuma_api: KumaAPI 20.1.9-SNAPSHOT
		bettercombat: Better Combat 1.8.6+1.20.1
		cloth-config: Cloth Config v11 11.1.136
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.87
		combat-plus-core: Combat+ Core 1.1.0+1.20.1
			lilylib: LilyLib 1.1.3+1.20
			mm: Manningham Mills 2.3
		cookingforblockheads: Cooking for Blockheads 16.0.9
		cristellib: Cristel Lib 1.1.5
			blue_endless_jankson: jankson 1.2.3
		elementa: Elementa 670
		enchanted: Enchanted 3.1.2
		essential: Essential 1.3.5.5
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		farmersdelight: Farmer's Delight 1.20.1-2.2.4+refabricated
			porting_lib_accessors: Porting Lib Accessors 2.3.8+1.20.1
			porting_lib_base: Porting Lib Base 2.3.8+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.8+1.20.1
				porting_lib_common: Porting Lib Common 2.3.8+1.20.1
				porting_lib_core: Porting Lib Core 2.3.8+1.20.1
				porting_lib_entity: Porting Lib Entity 2.3.8+1.20.1
				porting_lib_extensions: Porting Lib Extensions 2.3.8+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.8+1.20.1
				porting_lib_gui_utils: Porting Lib Gui Utils 2.3.8+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.8+1.20.1
				porting_lib_transfer: Porting Lib Transfer 2.3.8+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.8+1.20.1
				reach-entity-attributes: Reach Entity Attributes 2.4.0
			porting_lib_config: Porting Lib Config 2.3.8+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.8+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.8+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.8+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.8+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.8+1.20.1
		farmersknives: Farmer's Knives 3.2
		fdjei: Just Enough Farmer's Recipes 1.0.1
		forgeconfigapiport: Forge Config API Port 8.0.1
		furniture: [Let's Do] Furniture 1.0.4
		geckolib: GeckoLib 4 4.4.9
			com_eliotlash_mclib_mclib: mclib 20
		glitchcore: GlitchCore 0.0.1.1
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
			net_jodah_typetools: typetools 0.6.3
		incendium: Incendium 5.3.5
		indium: Indium 1.0.34+mc1.20.1
		iris: Iris 1.7.5+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.12.2.51
		magistuarmory: Epic Knights Mod 9.18
		minecraft: Minecraft 1.20.1
		moretools: More Tools (Polymer) 1.5.0+1.20.1
		naturalist: Naturalist 4.0.3
		org_jetbrains_annotations: annotations 23.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		player-animator: Player Animator 1.0.2-rc1+1.20
		polymer-bundled: Polymer 0.5.20+1.20.1
			polymer-blocks: Polymer (Textured Blocks) 0.5.20+1.20.1
			polymer-common: Polymer (Common) 0.5.20+1.20.1
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
			polymer-core: Polymer (Core) 0.5.20+1.20.1
				polymer-networking: Polymer (Networking) 0.5.20+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.20+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.20+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.20+1.20.1
		sereneseasons: SereneSeasons 9.1.0.0
		skinlayers3d: 3d-Skin-Layers 1.7.4
		smartbrainlib: SmartBrainLib 1.15
		sodium: Sodium 0.5.11+mc1.20.1
		stateobserver: StateObserver 1.4.3
		t_and_t: Towns and Towers 1.12
		terrablender: TerraBlender 3.0.1.7
		treeharvester: Tree Harvester 9.1
		universalcraft: UniversalCraft 365
		vigilance: Vigilance 306
		waystones: Waystones 14.1.6
		xaerominimap: Xaero's Minimap 24.6.1
		xaeroworldmap: Xaero's World Map 1.39.2
	Loaded Shaderpack: ComplementaryUnbound_r5.3.zip
		Profile: HIGH (+0 options changed by user)
	Launched Version: fabric-loader-0.16.9-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.0 Core Profile Context 23.10.24.230718, ATI Technologies Inc.
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, $polymer-resources
	Current Language: en_us
	CPU: 16x AMD Ryzen 9 4900H with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['sP1cYram3nn'/372, l='ServerLevel[New World]', x=-47.78, y=69.00, z=152.74]]
	Data Packs: vanilla, fabric, resources/t_and_t_waystones_patch_1.19.2 (incompatible), $polymer-resources
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by Spicyramenn** [comment]
[latest.log](https://github.com/user-attachments/files/18193101/latest.log)

**Comment by Favouriteless** [comment]
This was fixed, just never closed the issue.
